### ISSUE TITLE
any plan to support bounce animation while dragging the sliding?

### ISSUE THREAD

**Issue by jinfagang** [letsar/flutter_slidable#106] opened 2019-11-17 14:22 UTC
Now the process looks like stiff and not very smooth.

**Comment by parth22** [comment] 2019-11-19 04:45
@jinfagang You can use [Animator](https://pub.dev/packages/animator) package for that.
```
secondaryActions: <Widget>[
          Animator(
            tween: Tween<double>(begin: 0.0, end: 1.0),
            curve: Curves.elasticOut,
            builder: (anim) => Transform.scale(
              scale: anim.value,
              child: IconSlideAction(
                caption: AppLocalizations.of(context).translate('Delete'),
                color: pinkColor,
                icon: Icons.delete,
                onTap: () {
                  if (dbHelper.isOffLineMode) {
                    offlineStatusMessage();
                    return;
                  }
                  _onYorList(listItem.id, index);
                },
              ),
            ),
          ),
        ],
```

**Comment by jinfagang** [comment] 2019-11-19 06:19
@parth22 thanks, I will have a try.

**Comment by letsar** [comment] 2020-11-08 15:29
Duplicate of #103

**Closed by letsar** 2020-11-08 15:29 UTC
