### ISSUE TITLE
onTap doesn't work

### ISSUE THREAD

**Issue by ndemari** [letsar/flutter_slidable#47] opened 2019-02-03 17:38 UTC
Adding a callback function for IconSlideAction to onTap doesn't work no matter what I do.

**Comment by ignertic** [comment] 2019-03-05 09:21
It seems it's triggered when the widgets build, really need solution to this

**Comment by ignertic** [comment] 2019-06-04 17:56
was this ever solved?

**Comment by letsar** [comment] 2020-11-08 14:27
Cannot reproduce, I'm closing this. If there's still an issue for you, please fill an new issue with the exact steps how to reproduce this.

**Closed by letsar** 2020-11-08 14:27 UTC
