### ISSUE TITLE
Is there a hideAllActionsThreshold or equivalent?

### ISSUE THREAD

**Issue by Addictorator** [letsar/flutter_slidable#96] opened 2019-09-12 03:22 UTC
I understand there's a showAllActionsThreshold parameter in Slidable class which can be used to adjust the threshold / minimum directional motion offset needed in a swipe to display all the actions, but it seems like it doesn't affect the minimum directional motion needed to close it by swiping in the reverse direction when open. Is there a way to adjust this value, or at least make it the same as showAllActionsThreshold?

**Comment by cassioseffrin** [comment] 2020-07-10 20:28
Hello!

This feature is really important. The default threshold to close is too high and I cannot find a way to change it.

@Addictorator did you found a solution?

Any help on this will be appreciated!

**Comment by letsar** [comment] 2020-11-08 15:26
Duplicate of #62

**Closed by letsar** 2020-11-08 15:26 UTC
Labels: duplicate
