### ISSUE TITLE
Widget tests using slidable not confirming that the mock method was called

### ISSUE THREAD

**Issue by Baileypollard** [letsar/flutter_slidable#81] opened 2019-06-13 15:05 UTC
```
 @override
  Widget build(BuildContext context) {
    return Slidable(
      enabled: _invoice.state == InvoiceState.SKIPPED ? false : true,
      controller: skipController,
      actionExtentRatio: 0.20,
      actionPane: SlidableDrawerActionPane(),
      secondaryActions: <Widget>[
        IconSlideAction(
          caption: 'Skip',
          onTap: () async {
            await locator<InvoiceListModel>()
                .setInvoiceState(_invoice, InvoiceState.SKIPPED);
          },
          color: Colors.orange,
          icon: FontAwesomeIcons.forward,
        ),
      ],
      child: GestureDetector(
        //Open Invoice Item activity
        onTap: () {},
        child: Card(
          elevation: 10.0,
          child: Row(
            children: <Widget>[
              Flexible(
                child: ListTile(
                  leading: _buildInvoiceStateIcon(),
                  title: Text(
                    'Invoice #${_invoice.invoiceNumber}',
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  subtitle: Text(
                      '2001300 This is the first item in this invoice',
                      style: TextStyle(color: Colors.grey.shade800)),
                  trailing: Text(_invoice.invoiceDate),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  testWidgets('Check that the Invoice cell can be skipped',
      (WidgetTester tester) async {
    String invoiceNumber = '1234';
    InvoiceState state = InvoiceState.NOT_CHECKED_IN;
    String date = '2019-09-09';
    String customerId = '1234444';

    Invoice invoice = Invoice(
        customerId: customerId,
        invoiceNumber: invoiceNumber,
        state: state,
        invoiceDate: date);

    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: InvoiceCell(invoice, skipController),
        ),
      ),
    );

    expect(find.byType(IconSlideAction), findsNothing);

    await tester.dragFrom(Offset.zero, Offset(-1, 0));

    await tester.pump(Duration(seconds: 3));

    expect(find.byType(IconSlideAction), findsOneWidget);

    await tester.tap(find.byType(IconSlideAction));

    await tester.pumpAndSettle(Duration(seconds: 4));

    //Slidable for some reason wont verify that the correct method was called in a test.
    //This will always fail even though the manual test will pass.
    verify(locator<InvoiceListModel>()
    .setInvoiceState(invoice, InvoiceState.SKIPPED)).called(1);
  });
```

It appears that this is constantly failing even though manual tests pass fine. The problem appears the be that the mock.setInvoiceState(...) is not being recognized when the tester taps on the icon.

**Comment by letsar** [comment] 2020-11-08 15:14
I will create a test for this use case in my refactoring to see if I reproduce.

**Comment by normancarcamo** [comment] 2021-01-11 11:24
😕  same thing here. Are you for some reason avoiding the tap event on the actions? I can't test it, only manual testing.

**Comment by letsar** [comment] 2021-07-20 19:09
Can you test it with the 1.0 version?

**Comment by FabianVarela** [comment] 2021-07-26 17:28
Hi, @letsar I check version 1.0.0 and the test to drag has worked, thanks a lot. However, when I test the tap, I think that doesn't work. I set my widget test and the warning when I test the tap

```dart
    testWidgets('Slide a $TodoItem', (tester) async {
      // Custom widget list
      await _pumpMainScreen(tester, TodoListView(category: category));
      await tester.pumpAndSettle();

      // Another custom widget
      final foundItemList = find.descendant(
        of: find.byType(ListView),
        matching: find.byType(TodoItem),
      );
      expect(foundItemList, findsOneWidget);

      await tester.drag(foundItemList, const Offset(50, 0));
      await tester.pump(const Duration(seconds: 3));

      // Found the slide action, that's ok
      final foundSlideAction = find.byType(SlidableAction);
      expect(foundSlideAction, findsOneWidget);
      expect(find.byIcon(Icons.edit), findsOneWidget);

      // HERE gets the warning
      await tester.tap(foundSlideAction);
      await tester.pumpAndSettle();
    });
```

This is the warning

```bash
Warning: A call to tap() with finder "exactly one widget with type "SlidableAction" (ignoring offstage widgets): SlidableAction" derived an Offset (Offset(-114.0, 293.3)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
Indeed, Offset(-114.0, 293.3) is outside the bounds of the root of the render tree, Size(800.0, 600.0).
The finder corresponds to this RenderBox: RenderConstrainedBox#8c2c0
The hit test result at that offset is: HitTestResult(HitTestEntry#b9b15(RenderView#3a2dd)
```

Also, set this code to silence the warning, but doesn't work
```bash
To silence this warning, pass "warnIfMissed: false" to "tap()".
```

I was seeing your test, but I didn't see anything similar. I hope can you help me. Tanks again

**Comment by letsar** [comment] 2021-08-01 17:32
I think that's because the `Slidable` closed itself after the drag (because the touch pointer is released). You should use another method to let the `Slidable` dragged or make sure it will open by dragging it over the `openThreshold`.

In **action_pane_motions_test.dart** I used this extension for this kind of use case:
```dart
extension on WidgetTester {
  Future<void> dragAndHold(Finder finder, Offset offset) async {
    final gesture = await startGesture(getCenter(finder));
    await gesture.moveBy(offset);
    await pump();
  }
}
```

**Comment by letsar** [comment] 2022-07-10 10:20
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.

**Closed by letsar** 2022-07-10 10:20 UTC
Labels: waiting for user response
