### ISSUE TITLE
How can i show actions by default or the card slided by default to know user that this card is swipeable?

### ISSUE THREAD

**Issue by taimoorsarwar** [letsar/flutter_slidable#137] opened 2020-05-23 20:56 UTC

**Comment by timosturm** [comment] 2020-06-05 18:37
https://github.com/letsar/flutter_slidable#how-can-i-open-the-slidable-programmatically

This might be helpful.

**Comment by letsar** [comment] 2020-11-08 20:04
Dupe of #67

**Closed by letsar** 2020-11-08 20:04 UTC
